from ctypes import *

def to_ptr(data: bytes | bytearray) -> c_char_p:
	...

def free_mem(memory: c_void_p) -> None:
	...

def rev16(data: c_char_p, dlen: c_int32) -> None:
	...

def crc32(data: c_char_p, dlen: c_int32) -> c_int32:
	...

def coff_load(data: c_char_p, dlen: c_int32, coff: c_void_p) -> c_bool:
	...

def coff_sects(coff: c_void_p, sects: c_void_p) -> c_bool:
	...

def coff_copy_sects(taddr: int, tlen: int, src: c_char_p, dst: c_char_p, sects: c_void_p, nsect: int):
	...

def error():
	...