


spec = CompilerSpec("clang")
spec.set_rsp("@{}", ".rsp")
spec.add_str("-c")
spec.add_opts()
spec.add_incs("-I{}")
spec.add_defs("-D{}")
spec.add_str(["-o"])
spec.add_outf(".o")
spec.add_str(["-MMD", "-MF"])
spec.add_deps(".d")
spec.add_src()

spec = LinkerSpec("ld.lld")
spec.set_rsp("@{}", "link.rsp")
spec.add_opts()
spec.add_str("--image_input=", True)
spec.add_inf("bin", True)
spec.add_str(",.sect_name,", True)
spec.add_ins("addr")
spec.add_str("-o")
spec.add_outf("elf")
spec.add_libs("-L{}")
spec.add_objs("{}")